name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python: [3.8]
        os: [ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          # Latest at time of writing
          version: 1.1.7
          virtualenvs-create: true
          virtualenvs-in-project: true
      # - name: Install Poetry
      #   run: |
      #     pipx install 'poetry @ git+https://github.com/master/poetry.git@master'
      #     poetry config virtualenvs.create true
      #     poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        #if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          # Workaround for a bug with poetry on GHA
          #poetry export -f requirements.txt --output requirements.txt
          poetry install -vvv --no-interaction --no-root

      - name: Lint
        run: make lint
